server:
  port: 8080

spring:
  profiles:
    active: default

# Default profile (local development and testing)
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/pricedb
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false  # Disable open-in-view to avoid potential performance issues

  data:
    redis:
      host: localhost
      port: 6379
      password: Ab123456

logging:
  level:
    com.jack.priceservice: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html

initial:
  price: 100.00

# Docker profile (for running in containers)
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/pricedb
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false  # Disable open-in-view to avoid potential performance issues

  data:
    redis:
      host: redis
      port: 6379
      password: Ab123456

logging:
  level:
    com.jack.priceservice: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

initial:
  price: 100.00
